// Each should have a category attribute
// filter by category on categoy pages
// get all category and link to next one


export const images = [
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1708478564/Venom_a4xewj.jpg'],
    title: 'thank You for the Venom',
    handle: "/insert-angel",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>February 2024.</p>`,
    year: 2024,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1708478566/Parker_Bacall_Corpsey_Frame_1_g6befm.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1708478566/Parker_Bacall_Corpsey_Frame_2_tlamtz.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1708478568/Parker_Bacall_Corpsey_Frame_3_idgqtq.jpg'],
    title: 'Corspey Gets Extenstiental',
    handle: "/corpsey",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital Illustration',
    description: `<p>Comic panels that I did for the <a href="https://corpsey.trubble.club/" rel=”noopener noreferrer” target="_blank" Infinite Corpse</a>, a chain comic with 556 artists! November 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1702349029/UnderVolted_Demo_rinl9n.jpg'],
    title: 'Insert Angel',
    handle: "/insert-angel",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital Illustration',
    description: `<p>Album artwork commisioned for <a rel=”noopener noreferrer” target="_blank" href="https://undervolted.bandcamp.com/album/insert-disc-1">Undervolted's</a> first release, <a rel=”noopener noreferrer” target="_blank" href="https://undervolted.bandcamp.com/album/insert-disc-1">Insert Disc One</a>. November 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1695344466/3B79AE5F-E645-4517-ABD4-E9942305CFF7_idlhji.jpg'],
    title: 'Sold my Soul',
    handle: "/sold-my-soul",
    categories: ['paintings', 'home'],
    medium: 'Acrylic on Canvas',
    description: `<p>September 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1695344995/sketchbook_5_ssf60l.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1695344997/sketchbook_6_njhoek.jpg'],
    title: 'Sketchbook Cover #5 ',
    handle: "/sketchbook-cover-5",
    categories: ['paintings'],
    medium: 'Acrylic on sketchbook',
    description: `<p>September 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1695344996/lil_painter_luwt0y.jpg'],
    title: 'Lil Demon',
    handle: "/lil-demon",
    categories: ['paintings'],
    medium: 'Acrylic Canvas',
    description: `<p>August 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1695344481/Untitled_Artwork_1_ngsd9j.png'],
    title: 'Gone far Away ',
    handle: "/gone-far-away",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital Illustration',
    description: `<p>Featured in <a rel=”noopener noreferrer” target="_blank"  href="https://www.xzbtlife.com/" >XZBT Galleries</a> Monochrome art show in September 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1695344474/Untitled_Artwork_2_s6hqjt.png'],
    title: 'Battle Scars ',
    handle: "/battle-scars",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital Illustration',
    description: `<p>Featured in <a rel=”noopener noreferrer” target="_blank"  href="https://www.xzbtlife.com/" >XZBT Galleries</a> Monochrome art show in September 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1691449398/trouble_ax9dg7.jpg'],
    title: 'Troubles ',
    handle: "/troubles",
    categories: ['paintings', 'home'],
    medium: 'Acrylic and Screen Print on Canvas',
    description: `<p>Featured in <a rel=”noopener noreferrer” target="_blank"  href="https://www.xzbtlife.com/" >XZBT Galleries</a> Pop art show in August 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1691449082/Untitled_Artwork_kvenoo.png'],
    title: 'Flea Poster August 2023 ',
    handle: "/flea-poster-august",
    categories: ['designs', 'home'],
    medium: 'Digital Illustration',
    description: `<p>Poster for Los Feliz Flea Market August 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1691449338/IMG_0169_vkl28v.jpg'],
    title: 'Mother and Father ',
    handle: "/mother-father",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>Drawing made for my Mom for her birthday! 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684627558/I_m_so_glad_it_will_end_iwgiln.jpg'],
    title: 'This will end',
    handle: "/this-will-end",
    categories: ['home', 'paintings'],
    medium: 'Acrylic on canvas',
    description: `<p>Part of a series of three. 2023.</p>`,
    year: 2023
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1680563695/FALLEN_szv0bn.png'],
    title: 'Fallen Mural',
    handle: "/fallen-mural",
    categories: ['home', 'murals'],
    medium: 'Spray Paint on Alley Wall',
    description: `<p>First large scale outdoor mural I created. Part of a large scale installation at <a rel=”noopener noreferrer” target="_blank" href="https://www.denverartsociety.org/">Denver Art Society </a> in Denver, CO to raise aqareness for breast cancer. 2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1680563697/SEPUKKU_bqqpo0.png'],
    title: 'Seppuku Mural',
    handle: "/seppuku-mural",
    categories: ['home', 'murals'],
    medium: 'Acrylic Paint on Wall',
    description: `<p>The second Mural I worked on. Seppuku stands inside the studio space, next to works of other talented artists at <a rel=”noopener noreferrer” target="_blank" href="https://www.denverartsociety.org/">Denver Art Society</a> in Denver, CO. 2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1680149037/8_ze2th4.png', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1684805117/21_ub5yp8.png', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1684805121/29_frsdwe.png', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1684805122/7_t1vk6g.png'],
    title: '100 Skulls',
    handle: "/100-skulls",
    categories: ['home', 'digital-illustrations'],
    medium: 'Digital',
    description: `<p>This image was producted in multiple colorways as 16"x16" prints. Color work was done with long time friend and collaborar with Eduardo Miller, founder of <a href="https://highstoneshop.com/" rel=”noopener noreferrer” target="_blank">Highstone</a>. 2022.</p>`,
    year: 2023
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231391/Untitled_Artwork_9_j1llfs.png'],
    title: 'For my Love',
    handle: "/for-my-love",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>For my Love, Peyton. 2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1680149030/final4_amutft.png'],
    title: 'The End',
    handle: "/the-end",
    categories: ['home', 'prints'],
    medium: 'Intaglio Print, Mixed Media',
    description: `<p>Final Intaglio print for a course at the University of Denver. Main print made up of a few different daily sketches. Accents consisting of other Intaglio and Relief prints were sewn on. 2018.</p>`,
    year: 2018
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1680149032/totem_vkzr1y.png'],
    title: 'Totem',
    handle: "/totem",
    categories: ['home', 'illustrations'],
    medium: 'Pen, markers and colored pencils on paper',
    description: `<p>2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684617852/Bacall_Ugly_and_Good_n6xgsj.jpg'],
    title: 'Ugly and Good',
    handle: "/ugly-and-good",
    categories: ['paintings', 'home'],
    medium: 'Acrylic on canvas',
    description: `<p>Part of a series of three. 2023.</p>`,
    year: 2023
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684617862/Eveyone_I_know_final_estoqo.jpg'],
    title: 'Everyone I Know is Gonna Die',
    handle: "/everyone-i-know",
    categories: ['paintings'],
    medium: 'Acrylic on canvas',
    description: `<p>Part of a series of three. 2023.</p>`,
    year: 2023
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684804540/bacall_Carrion_kt2ush.jpg'],
    title: 'Carry on',
    handle: "/carrion",
    categories: ['paintings', 'home'],
    medium: 'Acrylic on canvas',
    description: `<p>Shown at Angel City Brewery in Los Angeles, CA. 2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685156114/pooo_csden0.gif'],
    title: 'Fried Gnome',
    handle: "/friend-gnome",
    categories: ['animations', 'home'],
    medium: 'Digital Animation',
    description: `<p>Animation made for recording artist <a href="https://tothemaxshrager.bandcamp.com/music" rel=”noopener noreferrer” target="_blank" >Max Sharger</a>. Used for promotion and Spotify backdrop. 2023.</p>`,
    year: 2023
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805190/Untitled_Artwork_2_hytz3v.gif'],
    title: 'Blood Guy',
    handle: "/blood-guy",
    categories: ['animations'],
    medium: 'Digital Animation',
    description: `<p>Animation made in Procreate as part of a series of three. 2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805183/Untitled_Artwork_3_t37poc.gif'],
    title: 'Skull split',
    handle: "/skull-split",
    categories: ['animations', 'home'],
    medium: 'Digital Animation',
    description: `<p>Animation made in Procreate as part of a series of three. 2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805182/Untitled_Artwork_wwp4dt.gif'],
    title: 'Young King',
    handle: "/young-king",
    categories: ['animations'],
    medium: 'Digital Animation',
    description: `<p>Animation made in Procreate as part of a series of three. 2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805172/Untitled_Artwork_13_ahoa5t.png'],
    title: '25 stair ollie',
    handle: "/25-stair-ollie",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805169/Untitled_Artwork_9_c6nwjr.png'],
    title: 'Blasphemous',
    handle: "/blasphemous",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Drawn on a photo of a church in Los Angeles. 2021.</p>`,
    year: 2021
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231362/Untitled_Artwork_19_o0ahzk.png'],
    title: 'Overwhelmed',
    handle: "/overwhelmed",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Featured in Nightmares Vol 1 Zine. 2021.</p>`,
    year: 2021
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805126/Untitled_Artwork_11_znp8cv.png'],
    title: 'Freaks',
    handle: "/freaks",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>Featured in Nightmares Vol 1 Zine. 2021.</p>`,
    year: 2021
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231359/IMG_6059_qcqppo.png'],
    title: 'Over Worked',
    handle: "/over-worked",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Featured in Nightmares Vol 1 Zine. 2021.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231359/IMG_6053_qbglru.png'],
    title: 'Under Valued',
    handle: "/under-valued",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Featured in Nightmares Vol 1 Zine. 2021.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805164/Untitled_Artwork_14_dvfnst.png'],
    title: 'When will it end',
    handle: "/when-will-it-end",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>Drawn on a photo taken by Emmett Batley. 2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805160/Untitled_Artwork_20_tyhqno.png'],
    title: 'Mush',
    handle: "/mush",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>Produced as 8.5"x11" prints. 2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805153/Untitled_Artwork_16_kk5njx.png'],
    title: 'Apocolypse',
    handle: "/apocolypse",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>Drawn on a photo shot by Jack Khal. 2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805150/Untitled_Artwork_10_u82niu.png'],
    title: 'Experimental Me',
    handle: "/experimental-me",
    categories: ['digital-illustrations', , 'home'],
    medium: 'Digital',
    description: `<p>Part of a series of 2. 2021.</p>`,
    year: 2021
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805136/IMG_0531_tmafw9.png'],
    title: 'Experimental Me Too',
    handle: "/experimental-me-too",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Part of a series of 2. 2021.</p>`,
    year: 2021
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805148/Untitled_Artwork_2_oov8n3.png'],
    title: 'Haters',
    handle: "/haters",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Album cover concept for <a href="https://soundcloud.com/princessspankxd" rel=”noopener noreferrer” target="_blank" >Spank</a>. 2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147630/Untitled_Artwork_7_haipoy.png'],
    title: 'Premiere Content',
    handle: "/premiere-conntent",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Collab with artist <a rel=”noopener noreferrer” target="_blank" href="https://www.joecapon.com/">Joe Capon</a>. 2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805139/Untitled_Artwork_3_rd7sti.png'],
    title: 'Look Out',
    handle: "/look-out",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>Produced as 8.5"x11" prints. 2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805136/Untitled_Artwork_15_ovxbio.png'],
    title: 'Above and Below',
    handle: "/above-and-below",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>Drawn on a photo taken by Emmett Batley. 2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805132/balloon_fo2pgv.jpg'],
    title: 'Cubist Hell',
    handle: "/cubist-hell",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>Produced as 2.5"x3.5" stickers. 2018.</p>`,
    year: 2018
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805126/IMG_0285_aa4yse.png'],
    title: 'Exploding Skeleton',
    handle: "/exploding-skeleton",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Inktober promt. 2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231392/IMG_0219_qrtlfc.png'],
    title: 'Bunny',
    handle: "/bunny",
    categories: ['digital-illustrations'],
    medium: 'Digital Illustration',
    description: `<p>Inktober Drawing. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231392/Untitled_Artwork_21_kpbd8o.png'],
    title: 'Broken',
    handle: "/broken",
    categories: ['digital-illustrations'],
    medium: 'Digital Illustration',
    description: `<p>Inktober Drawing. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231367/Untitled_Artwork_22_w9cvmq.png'],
    title: 'Gloom',
    handle: "/gloom",
    categories: ['digital-illustrations'],
    medium: 'Digital Illustration',
    description: `<p>Inktober Drawing. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231367/Untitled_Artwork_24_bqb181.png'],
    title: 'Mutant',
    handle: "/mutant",
    categories: ['digital-illustrations'],
    medium: 'Digital Illustration',
    description: `<p>Inktober Drawing. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231366/Untitled_Artwork_23_mzru47.png'],
    title: 'Joker',
    handle: "/joker",
    categories: ['digital-illustrations'],
    medium: 'Digital Illustration',
    description: `<p>Inktober Drawing. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231362/IMG_0235_ugmgfi.png'],
    title: 'X-ray',
    handle: "/x-ray",
    categories: ['digital-illustrations'],
    medium: 'Digital Illustration',
    description: `<p>Inktober Drawing. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231359/IMG_0253_lwvykv.png'],
    title: 'The Devil',
    handle: "/the-devil",
    categories: ['digital-illustrations'],
    medium: 'Digital Illustration',
    description: `<p>Inktober Drawing. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231359/IMG_0284_xhbqt6.png'],
    title: 'Skull Flowers',
    handle: "/skull-flowers",
    categories: ['digital-illustrations'],
    medium: 'Digital Illustration',
    description: `<p>Inktober Drawing. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231356/IMG_0232_j8fpcq.png'],
    title: 'Tourment (2019)',
    handle: "/tourment-digital",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital Illustration',
    description: `<p>Inktober Drawing. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805126/Untitled_Artwork_19_hdwu05.png'],
    title: 'Self Portrait',
    handle: "/self-portrait",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231376/IMG_0161_tamkz6.png'],
    title: 'Haze',
    handle: "/haze",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231366/Untitled_Artwork_27_xojmnf.png'],
    title: 'Dice Devil 1/2',
    handle: "/dice-devil-1-2",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231358/IMG_0371_2_zyit5y.png'],
    title: 'Dice Devil 2/2',
    handle: "/dice-devil-2-2",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231365/IMG_0428_2_kiokgq.png'],
    title: 'Fuck Covid',
    handle: "/fuck-covid",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231364/Untitled_Artwork_2_ng1mnc.png'],
    title: 'Dunce',
    handle: "/dunce",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2021.</p>`,
    year: 2021
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231363/Untitled_Artwork_16_m7fdb9.png'],
    title: 'Sword',
    handle: "/sword-digital",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2021.</p>`,
    year: 2021
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805123/Untitled_Artwork_4_gsz5jc.png'],
    title: 'Ancient Relic',
    handle: "/ancient-relic",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Produced as 2"x3.5" stickers. 2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147625/Untitled_Artwork_2_n1hce2.png'],
    title: 'Heretic',
    handle: "/heretic",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>Produced as 2"x3.5" stickers. 2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805116/IMG_0172_itk6oh.png'],
    title: 'Where Did Everybody Go',
    handle: "/where-did-everybody-go",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805115/IMG_5272_tkccqb.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1684805116/IMG_5280_wp6rbf.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1684805116/IMG_5288_wqgeyd.jpg'],
    title: 'Painted Skull',
    handle: "/painted-skull",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>Multiple colorways. Produced as 8.5"x11" prints. 2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805121/Untitled_Artwork_12_yrxith.png'],
    title: 'Inferno',
    handle: "/inferno",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805120/Untitled_Artwork_17_yvpcgb.png'],
    title: 'Seppuku',
    handle: "/seppuku-digital",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Digital translation of mural by the same name. 2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1684805144/Untitled_Artwork_1_qwhmbq.png'],
    title: 'Tour Poster',
    handle: "/tour-poster",
    categories: ['designs'],
    medium: 'Digital',
    description: `<p>Tour Poster for <a rel=”noopener noreferrer” target="_blank" href="https://laslossound.bandcamp.com/">Las Los</a>. 2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147641/Untitled_Artwork_1_mndz19.png'],
    title: 'Sraper',
    handle: "/scraper",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Drawn on a photo of the city skyline shot by Jack Kahl. 2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147663/Untitled_Artwork_9_j8669m.png'],
    title: 'Dead Wrong',
    handle: "/dead-wrong",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>Drawn on a photo of the city shot by Jack Kahl. 2019.<p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147664/Untitled_Artwork_10_oyy1gu.png'],
    title: 'Reaper',
    handle: "/reaper",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Drawn on a photo of the city skyline shot by Jack Kahl. 2019.</p>`,
    year: 2019
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147644/Untitled_Artwork_13_ydpfb8.png'],
    title: 'Flower Devil',
    handle: "/flower-devil",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p> Modified result of a GAN Algorithm. 2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147661/Untitled_Artwork_12_l2y4fe.png'],
    title: 'Flower Skull GAN',
    handle: "/flower-skull-gan",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p> Modified result of a GAN Algorithm. 2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147628/IMG_0732_hkzrwm.png'],
    title: 'Bleeding out',
    handle: "/bleeding-out",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p> Modified result of a GAN Algorithm. 2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147646/Untitled_Artwork_3_lngppc.png'],
    title: 'Warm hands',
    handle: "/warm-hands",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2021.</p>`,
    year: 2021
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147647/Untitled_Artwork_6_ca827k.png'],
    title: 'Sentimental Skull Promo',
    handle: "/sentimental-skull",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Unused Promo Image for Sentimental Skull. 2021.</p>`,
    year: 2021
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147651/Untitled_Artwork_14_gasttf.png'],
    title: 'Sit and Burn',
    handle: "/sit-and-burn",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2022.</p>`,
    year: 2022
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147658/Untitled_Artwork_5_x9po1r.png'],
    title: 'Knight',
    handle: "/knight",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147665/Untitled_Artwork_4_ppkufk.png'],
    title: 'Let Me Know What you Find',
    handle: "/let-me-know-what-you-find",
    categories: ['digital-illustrations', 'home'],
    medium: 'Digital',
    description: `<p>'Let Me Know What you Find' was burnt to a screen and continues to be printed and custom garments. 2020.</p>`,
    year: 2020
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1685147625/IMG_0736_wrqyzu.png'],
    title: 'DVP',
    handle: "/dvp",
    categories: ['digital-illustrations'],
    medium: 'Digital',
    description: `<p>Concept inspired by the band PUP. 2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686879046/IMG_0206_jesivd.jpg'],
    title: 'Univited',
    handle: "/uninvited",
    categories: ['murals', 'home'],
    medium: 'Spray Paint on wall',
    description: `<p>.Location not to be disclosed. 2021.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686879044/IMG_0977_hhhyew.jpg'],
    title: 'Unholy',
    handle: "/unholy",
    categories: ['murals'],
    medium: 'Spray Paint on wall',
    description: `<p>Location not to be disclosed. 2021.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686879042/IMG_0986_e49go5.jpg'],
    title: 'Unwelcome',
    handle: "/unwelcome",
    categories: ['murals'],
    medium: 'Spray Paint on wall',
    description: `<p>.Location not to be disclosed. 2021.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686880226/giphy_2_tuonek.gif'],
    title: 'Body Terror',
    handle: "/body-terror",
    categories: ['animations', 'home'],
    medium: 'digital',
    description: `<p>Inspired by an AJJ song of the same name. 2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686880230/giphy_copy_zvrzsm.gif'],
    title: 'Waking Nightmares',
    handle: "/waking-nightmares",
    categories: ['animations'],
    medium: 'digital',
    description: `<p>2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686889613/giphy_scfc1c.gif'],
    title: 'Cursed Sword',
    handle: "/cursed-sword",
    categories: ['animations', 'home'],
    medium: 'digital',
    description: `<p>2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686889681/giphy_h1sbhe.gif'],
    title: 'Blood on the Snow',
    handle: "/Blood on the Snow",
    categories: ['animations'],
    medium: 'digital',
    description: `<p>Collaboration with <a href="https://trizton.myportfolio.com/work" rel=”noopener noreferrer” target="_blank">Trizton Delbaugh</a>. 2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686880225/giphy_6_pyq7au.gif'],
    title: 'Flailing',
    handle: "/flailing",
    categories: ['animations'],
    medium: 'digital',
    description: `<p>2020.</p>`,
    year: 2021,
  },
  // {
  //   images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686880225/giphy_3_i1u3f5.gif'],
  //   title: 'Grave Warden',
  //   handle: "/grave-warden",
  //   categories: ['animations'],
  //   medium: 'digital',
  //   description: `<p>2020.</p>`,
  //   year: 2021,
  // },
  // {
  //   images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686880225/giphy_4_d9kmeq.gif'],
  //   title: 'Hell Flower',
  //   handle: "/hell-flower",
  //   categories: ['animations'],
  //   medium: 'digital',
  //   description: `<p>2020.</p>`,
  //   year: 2020,
  // },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686880238/giphy_7_z27waq.gif'],
    title: 'Melting Face',
    handle: "/melting-face",
    categories: ['animations'],
    medium: 'digital',
    description: `<p>2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686880225/giphy_5_xsh48r.gif'],
    title: 'Unsanctioned',
    handle: "/unsanctioned",
    categories: ['animations'],
    medium: 'digital',
    description: `<p>2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1686880225/giphy_1_zfffqm.gif'],
    title: 'My Hell',
    handle: "/my-hell",
    categories: ['animations'],
    medium: 'digital',
    description: `<p>2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042210/IMG_6075_nllwge.jpg'],
    title: 'Assorted Skeletons',
    handle: "/assorted Skeletons",
    categories: ['paintings'],
    medium: 'Acrylic on canvas and wood panels',
    description: `<p>2019.</p>`,
    year: 2019,
  },
  // {
  //   images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042210/IMG_7401_yuqbp5.jpg'],
  //   title: 'Crybaby!',
  //   handle: "/crybaby",
  //   categories: ['paintings'],
  //   medium: 'Mix media on canvas',
  //   description: `<p>Collaborative painting with Emmett Batley. 2019.</p>`,
  //   year: 2019,
  // },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042238/skullsdeck_nxhdkb.jpg'],
    title: 'Death Race',
    handle: "/death-race",
    categories: ['paintings', 'home'],
    medium: 'Acrylic on Skateboard Deck',
    description: `<p>2018.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042159/skulldeck_zbnaxg.jpg'],
    title: 'Death March',
    handle: "/death-march",
    categories: ['paintings'],
    medium: 'Acrylic on Skateboard Deck',
    description: `<p>2018.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042238/guydeck_m0ihdi.jpg'],
    title: 'Tourment',
    handle: "/tourment",
    categories: ['paintings'],
    medium: 'Acrylic on Skateboard Deck',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042211/IMG_3996_gdnlzv.jpg'],
    title: 'Floral Demons',
    handle: "/floral-demons",
    categories: ['paintings'],
    medium: 'Acrylic on Skateboard Deck',
    description: `<p>2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687049901/IMG_2817_litkfg.jpg'],
    title: 'Death to Hipsters',
    handle: "/death-to-hipsters",
    categories: ['paintings'],
    medium: 'Acrylic on wood panel',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042209/IMG_2677_e3w5at.jpg'],
    title: 'Death to Devils',
    handle: "/death-to-devils",
    categories: ['paintings'],
    medium: 'Acrylic on wood panel',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687049900/IMG_28171_tskisx.jpg'],
    title: 'Death to the dead',
    handle: "/death-to-the dead",
    categories: ['paintings', 'home'],
    medium: 'Acrylic on wood panel',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042208/IMG_3998_hywqzs.jpg'],
    title: 'Welcome to Hell',
    handle: "/welcome-to-hell",
    categories: ['paintings', 'home'],
    medium: 'Acrylic on skateboard deck',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  // {
  //   images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042206/IMG_8928_2_wfvxxx.jpg'],
  //   title: 'Unhinged',
  //   handle: "/unhinged",
  //   categories: ['paintings'],
  //   medium: 'Acrylic on beer vessels',
  //   description: `<p>2020.</p>`,
  //   year: 2020,
  // },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042204/IMG_6443_zreism.jpg'],
    title: 'Flower Goth',
    handle: "/flower-goth",
    categories: ['paintings'],
    medium: 'Spray paint on salvaged wood',
    description: `<p>2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042196/IMG_6125_2_lqsafp.jpg'],
    title: 'Music Maker',
    handle: "/music-maker",
    categories: ['paintings'],
    medium: 'Acrylic on salvaged record',
    description: `<p>2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042201/IMG_6118_q0sbpr.jpg'],
    title: 'Fiends',
    handle: "/fiends",
    categories: ['paintings'],
    medium: 'Acrylic on salvaged record',
    description: `<p>2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042205/IMG_2054_hus9te.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687042205/IMG_2055_rix638.jpg'],
    title: 'Skechbook cover #1',
    handle: "/sketchbook-cover-1",
    categories: ['paintings'],
    medium: 'Acrylic on sketchbook',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042203/IMG_6773_jtukch.jpg'],
    title: 'Skechbook Cover #2',
    handle: "/sketchbook-cover-2",
    categories: ['paintings'],
    medium: 'Acrylic on sketchbook',
    description: `<p>2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687049898/IMG_9188_ywxslf.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687049898/IMG_9189_c0ag8a.jpg'],
    title: 'Skechbook cover #4',
    handle: "/sketchbook-cover-4",
    categories: ['paintings'],
    medium: 'Acrylic on sketchbook',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  // {
  //   images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687042203/IMG_7878_2_a3h64h.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687042204/IMG_7879_2_rkjpms.jpg'],
  //   title: 'Skechbook cover #3',
  //   handle: "/sketchbook-cover-3",
  //   categories: ['paintings'],
  //   medium: 'Acrylic on sketchbook',
  //   description: `<p>2023.</p>`,
  //   year: 2023,
  // },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687053174/rat1_cevypn.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687053175/rat2_zepzsn.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687053170/rat3_w46wxl.jpg'],
    title: 'Basil',
    handle: "/basil",
    categories: ['prints'],
    medium: 'Etched photo plate print and mixed media',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687053171/burn1_qxk4xw.jpg'],
    title: 'Burn Them for You',
    handle: "/burn-them",
    categories: ['prints'],
    medium: 'Screen print',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050492/faceOG_mnp56n.png'],
    title: 'Washed out',
    handle: "/washed-out",
    categories: ['prints'],
    medium: 'Screen print',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050471/groe_aqzbjg.png'],
    title: 'Groe',
    handle: "/groe",
    categories: ['prints'],
    medium: 'Relief Print and Mixed Media',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050469/LargeWoodBlock_gaekcp.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687050487/IMG_5549_yykflf.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687050479/print1_whnltz.png'],
    title: 'Relfection',
    handle: "/reflection",
    categories: ['prints'],
    medium: 'Woodblock Print',
    description: `<p>Large scale Woodblock print, made for RMCAD month of Printmaking steamroller printing event. 2019.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050523/monday_im1yw7.png'],
    title: 'Monday',
    handle: "/monday",
    categories: ['prints'],
    medium: 'Relief print and mixed Media',
    description: `<p>2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050546/tuesday_g7dhro.png'],
    title: 'Tuesday',
    handle: "/tuesday",
    categories: ['prints'],
    medium: 'Relief print and mixed Media',
    description: `<p>2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050529/wed_slkthi.png'],
    title: 'Wednesday',
    handle: "/wednesday",
    categories: ['prints'],
    medium: 'Relief print and mixed Media',
    description: `<p>2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050542/thursday_dypeji.png'],
    title: 'Thursday',
    handle: "/thursday",
    categories: ['prints'],
    medium: 'Relief print and mixed Media',
    description: `<p>2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050535/friday_ryb0zg.png'],
    title: 'Friday',
    handle: "/friday",
    categories: ['prints', 'home'],
    medium: 'Relief print and mixed Media',
    description: `<p>2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050528/saturday_lliavl.png'],
    title: 'Saturday',
    handle: "/saturday",
    categories: ['prints'],
    medium: 'Relief print and mixed Media',
    description: `<p>2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050516/sunday_knr7cx.png'],
    title: 'Sunday',
    handle: "/sunday",
    categories: ['prints'],
    medium: 'Relief print and mixed Media',
    description: `<p>2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050508/torment_qc8iku.png'],
    title: 'Daily Torment',
    handle: "/daily-tourment",
    categories: ['prints', 'home'],
    medium: 'Lithograph',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050499/swing_zqagcv.png'],
    title: 'Swing',
    handle: "/swing",
    categories: ['prints'],
    medium: 'Lithograph',
    description: `<p>Part of an intallation at University of Denver, Art department. 2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050539/artist_b9yqva.png'],
    title: 'Artist`s Journey',
    handle: "/artists-journey",
    categories: ['prints'],
    medium: 'Lithograph',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050485/ghost1_gzhjqt.png'],
    title: 'Ghost',
    handle: "/ghost",
    categories: ['prints'],
    medium: 'Lithograph',
    description: `<p>Two Color Lithograph print. 2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050504/IMG_4837_rn87b0.jpg'],
    title: 'Prosiac Blues',
    handle: "/Prosiac Blues",
    categories: ['prints'],
    medium: 'Intaglio Print',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050478/watercolor_nhrlxv.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687050478/gum_emj4id.jpg'],
    title: 'Wrath',
    handle: "/wrath",
    categories: ['prints', 'home'],
    medium: 'Relief print and Mixed Media',
    description: `<p>2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050472/sat2_phxoyk.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687050475/sat_uq5ux7.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687050470/sat5_f50err.jpg'],
    title: 'Hiding',
    handle: "/hidng",
    categories: ['prints', 'home'],
    medium: 'Intaglio print and Mixed Media',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687050462/drop_p92svw.jpg', 'https://res.cloudinary.com/dpdnba5be/image/upload/v1687050462/2left_dbuh3g.jpg'],
    title: 'Lost',
    handle: "/lost",
    categories: ['prints'],
    medium: 'Relief Print',
    description: `<p>2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220340/IMG_9206_x2ftnl.jpg'],
    title: 'Father`s Day',
    handle: "/fathers-day",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>For my Dad. 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220361/skater_eqz0tc.jpg'],
    title: 'Skater',
    handle: "/skater",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220417/IMG_6972_n5pquf.jpg'],
    title: 'Fear Me',
    handle: "/fear-me",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220413/husk_ulcfnr.png'],
    title: 'Husk',
    handle: "/husk",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220355/IMG_7606_j34juh.jpg'],
    title: 'It`s Over',
    handle: "/its-over",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220412/IMG_1776_iqytos.jpg'],
    title: 'Guts',
    handle: "/guts",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220403/surreal_uht0ia.png'],
    title: 'Secret World',
    handle: "/secret-world",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220398/IMG_0611_hlhp7e.jpg'],
    title: 'Fuckboi',
    handle: "/fuckboi",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220398/berrygood_khgttb.png'],
    title: 'Just Flowers',
    handle: "/just-flowers",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220398/IMG_6505_j2qgrr.jpg'],
    title: 'Politicized',
    handle: "/politicized",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220394/heads_arek3b.png'],
    title: 'Tourment 2018',
    handle: "/tourment-2018",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220387/IMG_0556_k5482z.jpg'],
    title: 'Burnt out',
    handle: "/burnt-out",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2016.</p>`,
    year: 2016,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220380/bowie_i4csio.png'],
    title: 'Bowie`s Skull',
    handle: "/bowie-skull",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220379/IMG_4569_u3gzoh.jpg'],
    title: 'April',
    handle: "/april",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220364/IMG_9088_rjxefr.jpg'],
    title: 'Majora',
    handle: "/majora",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220378/IMG_8691_pywy9z.jpg'],
    title: 'Cozy',
    handle: "/cozy",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220371/goth_tgliyg.png'],
    title: 'Goth',
    handle: "/goth",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220370/IMG_4035_yppe8o.jpg'],
    title: 'Sacred',
    handle: "/sacred",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220370/enchant_lf9gag.png'],
    title: 'Hex',
    handle: "/hex",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2018.</p>`,
    year: 2018,
  },

  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220367/IMG_0617_a7j4hv.jpg'],
    title: 'All Night Diner',
    handle: "/all-night-diner",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220365/IMG_7875_xiiwsu.jpg'],
    title: 'Ruined',
    handle: "/ruined",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220354/IMG_8273_wbbkwp.jpg'],
    title: 'Time to Die',
    handle: "/time-to-die",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220347/IMG_9044_ptp4cs.jpg'],
    title: 'Candles of Love',
    handle: "/candles-of-love",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220365/IMG_7652_qawqf5.jpg'],
    title: 'Casper',
    handle: "/casper",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220360/IMG_7722_rcbr1n.jpg'],
    title: 'Screwed',
    handle: "/screwed",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220357/IMG_7908_npobnk.jpg'],
    title: 'Flower Coffin',
    handle: "/flower-coffin",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220317/blood_aej6eu.png'],
    title: 'Blood',
    handle: "/blood",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220352/IMG_9087_woit1x.jpg'],
    title: 'Goodnight',
    handle: "/goodnight",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220352/IMG_0295_fiskkt.png'],
    title: 'Catalyst',
    handle: "/catalyst",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2017.</p>`,
    year: 2016,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220379/IMG_7359_mlqbie.jpg'],
    title: 'Hollow',
    handle: "/hollow",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220351/IMG_8799_tir59n.jpg'],
    title: 'Temptation',
    handle: "/temptation",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220346/IMG_8676_y1rbsx.jpg'],
    title: 'Keep it to Your Self',
    handle: "/keep-it-to-your-self",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220350/IMG_9043_xea2rm.jpg'],
    title: 'Just for You',
    handle: "/just-for-you",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>Inspired by <a href="https://vodkabreadbowl.bandcamp.com/music"rel=”noopener noreferrer” target="_blank" >Vodka Breadbowl</a>. 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220380/new_xrckkv.jpg'],
    title: 'Foliage',
    handle: "/foliage",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220347/IMG_0610_cvijiv.jpg'],
    title: 'What`s Left of Me',
    handle: "/whats-left-of-me",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220347/IMG_8800_xsdrlf.jpg'],
    title: 'Evil',
    handle: "/evil",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687923584/ghoul_uuvefi.png'],
    title: 'Ghoul ',
    handle: "/ghoul-illustration",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>Inktober 2018</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687923585/goblin_pntr2i.png'],
    title: 'Zombie ',
    handle: "/zombie",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>Inktober 2018</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220346/IMG_4905_w31fjw.jpg'],
    title: 'Emo Farmer',
    handle: "/emo-farmer",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220344/IMG_8179_qxfwvl.jpg'],
    title: 'Fucked Twice',
    handle: "/fucked-twice",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220343/IMG_7985_yorlpr.jpg'],
    title: 'The Keeper',
    handle: "/the-keeper",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220341/flowerskull_ihijya.png'],
    title: 'Flower Goth',
    handle: "/flower-goth-og",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220341/IMG_8032_zwvj5b.jpg'],
    title: 'Twins',
    handle: "/twins",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220339/IMG_8122_oc9eyb.jpg'],
    title: 'Elder',
    handle: "/elder",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220339/IMG_8218_ezyu2k.jpg'],
    title: 'Charmed',
    handle: "/charmed",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220338/IMG_8240_wuhdff.jpg'],
    title: 'Curesed',
    handle: "/cursed-2023",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220347/IMG_8221_lvszpy.jpg'],
    title: 'Goblin',
    handle: "/goblin",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220338/IMG_7928_dl4ubw.jpg'],
    title: 'Stabbed',
    handle: "/stabbed",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220338/IMG_7755_uqvz9d.jpg'],
    title: 'Entwined',
    handle: "/entwined",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220335/IMG_0627_fjoici.jpg'],
    title: 'Poor You',
    handle: "/poor-you",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220336/IMG_1577_vs747y.jpg'],
    title: 'Rotten Punk',
    handle: "/rotten-punk",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220335/IMG_7601_pqwrmr.jpg'],
    title: 'Fancy',
    handle: "/fancy",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220335/IMG_7648_sqdvd4.jpg'],
    title: 'Skeleton Pimp',
    handle: "/skeleton-pimp",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220334/IMG_0626_qdstxs.jpg'],
    title: 'Tourmnet (2021)',
    handle: "/tourmnet-2021",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220333/IMG_3700_m51y22.jpg'],
    title: 'Bold',
    handle: "/bold",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220332/IMG_7699_ingn7s.jpg'],
    title: 'Float',
    handle: "/float",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220331/IMG_0628_mfahmb.jpg'],
    title: 'Board',
    handle: "/board",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220331/IMG_7784_s7slmh.jpg'],
    title: 'Eaten',
    handle: "/eaten",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220330/IMG_7362_jy3drx.jpg'],
    title: 'Don`t',
    handle: "/dont",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220328/IMG_7597_p0r1dt.jpg'],
    title: 'Masked',
    handle: "/masked",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220326/IMG_8317_qgeseq.jpg'],
    title: 'Ripper',
    handle: "/ripper",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220326/IMG_0623_lbjepu.jpg'],
    title: 'Split Personality',
    handle: "/split-personality",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220325/IMG_7339_wmzihb.jpg'],
    title: 'Flower Skull (2023)',
    handle: "/flower-skull-2023",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220324/IMG_0625_nillny.jpg'],
    title: 'Fending for Myself',
    handle: "/fending-for-myself",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220324/IMG_0613_qmtpgu.jpg'],
    title: 'Two Headed Boy',
    handle: "/two-headed-boy",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220324/IMG_0613_qmtpgu.jpg'],
    title: 'The Kid',
    handle: "/the-kid",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220323/IMG_7287_ey2ej9.jpg'],
    title: 'Morbid Stuff',
    handle: "/morbid-stuff",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220322/IMG_7245_npaivj.jpg'],
    title: 'Heavy',
    handle: "/heavy",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220321/IMG_7482_dye572.jpg'],
    title: 'Skeleton',
    handle: "/skeleton",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220319/IMG_0224_hwy09n.jpg'],
    title: 'Burning Bed',
    handle: "/burning-bed",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220319/IMG_0616_wvz7f8.jpg'],
    title: 'Traitor',
    handle: "/traitor",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220318/IMG_0612_zp0qdw.jpg'],
    title: 'Dream Smoker',
    handle: "/dream-smoker",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220318/1265FA65-3E33-4818-ACE8-CEEB0304154E_atqxbt.jpg'],
    title: 'Basil',
    handle: "/basil-drawing",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687220318/6FAB9A24-6478-44AF-BDA4-2DC20B7A5C63_l0doc5.jpg'],
    title: 'Gang',
    handle: "/gang",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231880/6A83E4A7-94DF-4C8D-B47F-C98CFCC367D2_pswvch.jpg'],
    title: 'Whiping Her Lips',
    handle: "/whiping-her-lips",
    categories: ['illustrations', 'home'],
    medium: 'Illustration',
    description: `<p>I consider this one of my definitive works. This piece holds a lot of weight for me as it was one of the first that contained a strong meaning. It catalysted me to draw every day in 2018 and now again in 2023 to improve my technical skills. 2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225085/Untitled_Artwork_15_pobr3h.png'],
    title: 'Flower Skull (GAN)',
    handle: "/flower-skull-gan-design",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. Made from altered output from Generative adversarial network. 2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688683695/Untitled_Artwork_14_copy_poo7v1.jpg'],
    title: 'Heretic',
    handle: "/heretic-design",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225084/Untitled_Artwork_13_copy_x5xqou.png'],
    title: 'Las Los',
    handle: "/las-los",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for the band <a href="https://laslossound.bandcamp.com/" rel=”noopener noreferrer” target="_blank" >Las Los</a>. 2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225084/yellants_pihoce.png'],
    title: 'Yellnats Logo',
    handle: "/yellnats-logo",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Logo for the Denver based band <a href="https://theyellnats.bandcamp.com/" rel=”noopener noreferrer” target="_blank" >The Yellnats</a>. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225083/Untitled_Artwork_16_yma18m.png'],
    title: 'Las Los Logo',
    handle: "/las-los-logo",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Logo for the band <a href="https://laslossound.bandcamp.com/" rel=”noopener noreferrer” target="_blank" >Las Los</a>. 2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225082/Untitled_Artwork_13-2_vpljns.jpg'],
    title: 'Masked Demon',
    handle: "/masked-demon",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688683695/Untitled_Artwork_12_copy_j1goa1.jpg'],
    title: 'Untitled',
    handle: "/untitled",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225080/Sentimental_Skull_New_2022_vxrwun.jpg'],
    title: 'Morbid',
    handle: "/morbid",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225079/Untitled_Artwork_9_hgqvdp.png'],
    title: 'Skull Spank',
    handle: "/skull-spank",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Designed and screen-printed in limited quanties for <a href="https://soundcloud.com/princessspankxd" rel=”noopener noreferrer” target="_blank" >Spank</a>. 2023.</p>`,
    year: 2023,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231335/0A861E3F-3B7B-4F97-9E57-3626E6E3B663_hupmtw.jpg'],
    title: 'Rotten Punks',
    handle: "/rotten-punks",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Sticker design, 2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225318/Untitled_Artwork_14_jzvljs.jpg'],
    title: 'Sentimental Skull',
    handle: "/sentimental-skull-design",
    categories: ['designs', 'home'],
    medium: 'Digital Design',
    description: `<p>Seminal design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688685188/Untitled_Artwork_17_copy_dlmoqk_u4gfkx.jpg'],
    title: 'Two Headed Boy',
    handle: "/two-headed-boy-design",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Seminal design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225078/ghost_2_njfyeh.png'],
    title: 'Spectre',
    handle: "/spectre",
    categories: ['designs', 'home'],
    medium: 'Digital Design',
    description: `<p>Sticker design. 2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688683696/shoe_tuave2.jpg'],
    title: 'Tradition',
    handle: "/tradition",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Tattoo design. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225074/blue_z4hwdr.png'],
    title: 'Future Apologies 1/2',
    handle: "/future-apologies-1-2",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225075/pink_ier9m8.png'],
    title: 'Future Apologies 2/2',
    handle: "/future-apologies-2-2",
    categories: ['designs', 'home'],
    medium: 'Digital Design',
    description: `<p>2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225077/draw_devum9.png'],
    title: 'Washed',
    handle: "/washed-design",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>T-shirt design. 2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688683693/tat_cwt2wz.jpg'],
    title: 'Scribble',
    handle: "/scribble",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Tattoo design. 2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225076/flower_goth_pi8v45.png'],
    title: 'Flower Goth',
    handle: "/flower-goth-design",
    categories: ['designs', 'home'],
    medium: 'Digital Design',
    description: `<p>T-shirt design for Flower Goth. I screenprinting company I previously operated. 2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225076/shot_mi9d3q.png'],
    title: 'Burn them',
    handle: "/burn-them-design",
    categories: ['designs', 'home'],
    medium: 'Digital Design',
    description: `<p>T-shirt design. 2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225076/poem-2_sbalbu.png'],
    title: 'Living Skeletons',
    handle: "/living-skeletons",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Featured in Nightmares Vol 2 Zine. 2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688683692/Shape_80_a2ugml.jpg'],
    title: 'Quitter',
    handle: "/quitter",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>T-shirt design. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688683692/Shape_110_wqgr70.jpg'],
    title: 'Raven',
    handle: "/raven",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>T-shirt design. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688683692/Shape_87_d8stcl.jpg'],
    title: 'Dead',
    handle: "/dead",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>T-shirt design. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687303783/Shape_172_rretzs.jpg'],
    title: 'Tuesday',
    handle: "/tuesday-design",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>T-shirt design. 2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688683692/Shape_79_r5cmki.jpg'],
    title: 'Flower Club',
    handle: "/flower-club",
    categories: ['designs', 'home'],
    medium: 'Digital Design',
    description: `<p>T-shirt design. 2017.</p>`,
    year: 2017,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687225075/IMG_0477_dl40dy.png'],
    title: 'Cursed',
    handle: "/cursed-design",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>T-shirt design. 2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688683692/Shape_76_qwnrhu.jpg'],
    title: 'Skull Vase',
    handle: "/skull-vase",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688683692/Shape_78_r3ddpy.jpg'],
    title: 'Half Dead',
    handle: "/half-dead",
    categories: ['designs', 'home'],
    medium: 'Digital Design',
    description: `<p>T-shirt design. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1688685208/flowerl_j3h7ko.jpg'],
    title: 'Leviathan',
    handle: "/leviathan",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>T-shirt design. 2019.</p>`,
    year: 2019,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687234781/Screen_Shot_2023-06-19_at_9.18.38_PM_vrz9wr.png'],
    title: 'Trash',
    handle: "/trash",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Featured in Trash Zine by Louis Capon. 2018.</p>`,
    year: 2018,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231890/5_ij0npq.jpg'],
    title: 'Unknown Ghost',
    handle: "/unknown-ghost",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231335/3_uofuy2.jpg'],
    title: 'Floating',
    handle: "/floating-ghost",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231335/4_ipev2f.jpg'],
    title: 'Crying',
    handle: "/crying",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2022.</p>`,
    year: 2022,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231335/2_ywdldf.jpg'],
    title: 'The Stabbing',
    handle: "/the-stabbing",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231335/1_s7ziwq.jpg'],
    title: 'The Bleeding',
    handle: "/the-bleeding",
    categories: ['designs'],
    medium: 'Digital Design',
    description: `<p>Design for <a href="https://www.sentimentalskull.com/" rel=”noopener noreferrer” target="_blank" >Sentimental Skull</a>. 2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687303833/Untitled_Artwork_9_n5fkn9.png'],
    title: 'Facing Demons',
    handle: "/facing-demons",
    categories: ['digital-illustrations'],
    medium: 'Digital Illustration',
    description: `<p>Digitial Illustraition on a photo shot by Louis Capon. 2021.</p>`,
    year: 2021,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687231394/ok_ok_20201021121614332_omlhr3.png'],
    title: 'Blood on the Snow',
    handle: "/blood-on-the-snow-still",
    categories: ['digital-illustrations'],
    medium: 'Digital Illustration',
    description: `<p>Collaboration with <a href="https://trizton.myportfolio.com/work" rel=”noopener noreferrer” target="_blank">Trizton Delbaugh</a>. 2020.</p>`,
    year: 2020,
  },
  {
    images: ['https://res.cloudinary.com/dpdnba5be/image/upload/v1687923583/IMG_5925_qdzww2.jpg'],
    title: 'Eclipse ',
    handle: "/eclipse",
    categories: ['illustrations'],
    medium: 'Illustration',
    description: `<p>Collaboration with <a href="https://www.instagram.com/thomjberger/" rel=”noopener noreferrer” target="_blank">Thom J Berger</a>. 2019.</p>`,
    year: 2019,
  },
]
export function getImageByHandle(handle) {
  return images.filter((image) => image.handle === '/' + handle)[0];
}


export function getImagesByHandle(category) {
  return images.filter((image) => image.categories.includes(category))
}

